# Generated by Django 5.2.15 on 2026-06-23 06:30

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_organizacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='clave interna')),
                ('nombre_organizacion', models.CharField(max_length=150, unique=True, verbose_name='nombre o razón social')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'organización',
                'verbose_name_plural': 'organizaciones',
                'ordering': ['nombre_organizacion'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='nombre completo')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='teléfono')),
                ('correo', models.EmailField(blank=True, max_length=120, null=True, verbose_name='correo electrónico')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('organizacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actores.organizacion')),
                ('estatus_aseguradora', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=30, verbose_name='estatus')),
            ],
            options={
                'verbose_name': 'aseguradora',
                'verbose_name_plural': 'aseguradoras',
            },
            bases=('actores.organizacion',),
        ),
        migrations.CreateModel(
            name='PlataformaOperativa',
            fields=[
                ('organizacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actores.organizacion')),
                ('estatus_plataforma', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=30, verbose_name='estatus')),
            ],
            options={
                'verbose_name': 'plataforma operativa',
                'verbose_name_plural': 'plataformas operativas',
            },
            bases=('actores.organizacion',),
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('organizacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actores.organizacion')),
                ('estatus_socio', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=30, verbose_name='estatus')),
            ],
            options={
                'verbose_name': 'socio',
                'verbose_name_plural': 'socios',
            },
            bases=('actores.organizacion',),
        ),
        migrations.AddIndex(
            model_name='organizacion',
            index=models.Index(django.db.models.functions.text.Upper('clave_organizacion'), name='idx_org_clave'),
        ),
        migrations.AddIndex(
            model_name='organizacion',
            index=models.Index(django.db.models.functions.text.Upper('nombre_organizacion'), name='idx_org_nombre'),
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actores.persona')),
                ('estatus_conductor', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('BAJA', 'Baja')], default='ACTIVO', max_length=30, verbose_name='estatus')),
            ],
            options={
                'verbose_name': 'conductor',
                'verbose_name_plural': 'conductores',
            },
            bases=('actores.persona',),
        ),
        migrations.CreateModel(
            name='TitularPoliza',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actores.persona')),
                ('estatus_titular', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=30, verbose_name='estatus')),
            ],
            options={
                'verbose_name': 'titular de póliza',
                'verbose_name_plural': 'titulares de póliza',
            },
            bases=('actores.persona',),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(django.db.models.functions.text.Upper('nombre_completo'), name='idx_persona_nombre'),
        ),
        migrations.AddConstraint(
            model_name='aseguradora',
            constraint=models.CheckConstraint(condition=models.Q(('estatus_aseguradora__in', ['ACTIVA', 'INACTIVA'])), name='chk_aseguradora_estatus'),
        ),
        migrations.AddConstraint(
            model_name='plataformaoperativa',
            constraint=models.CheckConstraint(condition=models.Q(('estatus_plataforma__in', ['ACTIVA', 'INACTIVA'])), name='chk_plataforma_estatus'),
        ),
        migrations.AddConstraint(
            model_name='socio',
            constraint=models.CheckConstraint(condition=models.Q(('estatus_socio__in', ['ACTIVO', 'INACTIVO'])), name='chk_socio_estatus'),
        ),
        migrations.AddConstraint(
            model_name='conductor',
            constraint=models.CheckConstraint(condition=models.Q(('estatus_conductor__in', ['ACTIVO', 'INACTIVO', 'BLOQUEADO', 'BAJA'])), name='chk_conductor_estatus'),
        ),
        migrations.AddConstraint(
            model_name='titularpoliza',
            constraint=models.CheckConstraint(condition=models.Q(('estatus_titular__in', ['ACTIVO', 'INACTIVO'])), name='chk_titular_poliza_estatus'),
        ),
    ]
