# Generated by Django 5.2.15 on 2026-06-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='fecha_vencimiento_licencia',
            field=models.DateField(blank=True, null=True, verbose_name='vencimiento de licencia'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='numero_licencia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='número de licencia'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='tipo_licencia',
            field=models.CharField(blank=True, choices=[('A', 'A — Motocicleta'), ('B', 'B — Automóvil'), ('C', 'C — Camión ligero'), ('D', 'D — Autobús'), ('E', 'E — Vehículo especial')], max_length=1, null=True, verbose_name='tipo de licencia'),
        ),
        migrations.AddIndex(
            model_name='conductor',
            index=models.Index(fields=['numero_licencia'], name='idx_conductor_licencia'),
        ),
        migrations.AddConstraint(
            model_name='conductor',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_licencia__isnull', True), ('tipo_licencia__in', ['A', 'B', 'C', 'D', 'E']), _connector='OR'), name='chk_conductor_tipo_licencia'),
        ),
    ]
