# Generated by Django 5.2.15 on 2026-07-11 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actores', '0002_conductor_curp_conductor_fecha_vencimiento_licencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenciaConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('domicilio', models.TextField(verbose_name='domicilio')),
                ('telefono_contacto', models.CharField(max_length=30, verbose_name='teléfono de contacto')),
                ('parentesco', models.CharField(choices=[('MADRE', 'Madre'), ('PADRE', 'Padre'), ('HERMANO_A', 'Hermano/a'), ('PAREJA', 'Pareja'), ('HIJO_A', 'Hijo/a'), ('TIO_A', 'Tío/a'), ('PRIMO_A', 'Primo/a'), ('AMIGO_A', 'Amigo/a'), ('OTRO', 'Otro')], max_length=20, verbose_name='parentesco')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='actores.conductor', verbose_name='conductor')),
            ],
            options={
                'verbose_name': 'referencia personal de conductor',
                'verbose_name_plural': 'referencias personales de conductores',
                'ordering': ['conductor', '-fecha_creacion'],
                'indexes': [models.Index(fields=['conductor'], name='idx_referencia_conductor'), models.Index(fields=['telefono_contacto'], name='idx_referencia_telefono')],
                'constraints': [models.CheckConstraint(condition=models.Q(('parentesco__in', ['MADRE', 'PADRE', 'HERMANO_A', 'PAREJA', 'HIJO_A', 'TIO_A', 'PRIMO_A', 'AMIGO_A', 'OTRO'])), name='chk_referenciaconductor_parentesco')],
            },
        ),
    ]
