# Generated by Django 5.2.15 on 2026-06-23 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_color', models.CharField(max_length=50, unique=True, verbose_name='color')),
                ('abreviatura_color', models.CharField(blank=True, max_length=20, null=True, verbose_name='abreviatura')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colores',
                'ordering': ['nombre_color'],
            },
        ),
        migrations.CreateModel(
            name='EntidadFederativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entidad', models.CharField(max_length=80, unique=True, verbose_name='nombre de entidad')),
                ('abreviatura_entidad', models.CharField(blank=True, max_length=20, null=True, verbose_name='abreviatura')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'entidad federativa',
                'verbose_name_plural': 'entidades federativas',
                'ordering': ['nombre_entidad'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=80, unique=True, verbose_name='nombre de marca')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ['nombre_marca'],
            },
        ),
        migrations.CreateModel(
            name='AppTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_app', models.CharField(max_length=80, unique=True, verbose_name='nombre de la app')),
                ('estatus_app', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=30, verbose_name='estatus')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'aplicación de transporte',
                'verbose_name_plural': 'aplicaciones de transporte',
                'ordering': ['nombre_app'],
                'constraints': [models.CheckConstraint(condition=models.Q(('estatus_app__in', ['ACTIVA', 'INACTIVA'])), name='chk_app_transporte_estatus')],
            },
        ),
        migrations.CreateModel(
            name='ModeloVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo_comercial', models.CharField(max_length=100, verbose_name='modelo comercial')),
                ('version', models.CharField(blank=True, max_length=100, null=True, verbose_name='versión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='catalogos.marca', verbose_name='marca')),
            ],
            options={
                'verbose_name': 'modelo de vehículo',
                'verbose_name_plural': 'modelos de vehículo',
                'ordering': ['marca__nombre_marca', 'nombre_modelo_comercial', 'version'],
                'constraints': [models.UniqueConstraint(fields=('marca', 'nombre_modelo_comercial', 'version'), name='uq_modelo_vehiculo', nulls_distinct=False)],
            },
        ),
    ]
