# Generated by Django 5.2.15 on 2026-08-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('OPERADOR', 'Operador'), ('AUDITOR', 'Consulta (solo lectura)')], default='ADMINISTRADOR', max_length=20, verbose_name='rol'),
        ),
    ]
