# Generated by Django 5.2.15 on 2026-06-23 06:39

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actores', '0001_initial'),
        ('catalogos', '0002_datos_iniciales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplacamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placas', models.CharField(max_length=20, verbose_name='placas')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='fecha fin')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('entidad_federativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emplacamientos', to='catalogos.entidadfederativa', verbose_name='entidad federativa')),
            ],
            options={
                'verbose_name': 'emplacamiento',
                'verbose_name_plural': 'emplacamientos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_interno', models.CharField(blank=True, max_length=50, null=True, verbose_name='número interno')),
                ('anio_modelo', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='año modelo')),
                ('numero_serie', models.CharField(max_length=40, unique=True, verbose_name='número de serie / VIN')),
                ('estatus_unidad', models.CharField(choices=[('ACTIVA', 'Activa'), ('BAJA', 'Baja'), ('TALLER', 'En taller'), ('SIN_ASIGNAR', 'Sin asignar'), ('SINIESTRADA', 'Siniestrada'), ('VENDIDA', 'Vendida')], default='ACTIVA', max_length=30, verbose_name='estatus')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='catalogos.color', verbose_name='color')),
                ('modelo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='catalogos.modelovehiculo', verbose_name='modelo')),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'ordering': ['numero_interno', 'numero_serie'],
            },
        ),
        migrations.CreateModel(
            name='Tenencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_fiscal', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='año fiscal')),
                ('estatus_tenencia', models.CharField(choices=[('PAGADA', 'Pagada'), ('PENDIENTE', 'Pendiente'), ('NO_APLICA', 'No aplica'), ('DESCONOCIDA', 'Desconocida')], max_length=30, verbose_name='estatus')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='fecha de pago')),
                ('monto_tenencia', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenencias', to='vehiculos.vehiculo', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'tenencia',
                'verbose_name_plural': 'tenencias',
                'ordering': ['-anio_fiscal'],
            },
        ),
        migrations.CreateModel(
            name='TarjetaCirculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(blank=True, null=True, verbose_name='fecha de emisión')),
                ('fecha_vigencia_fin', models.DateField(verbose_name='vigencia hasta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('emplacamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarjetas_circulacion', to='vehiculos.emplacamiento', verbose_name='emplacamiento relacionado')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_circulacion', to='vehiculos.vehiculo', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'tarjeta de circulación',
                'verbose_name_plural': 'tarjetas de circulación',
                'ordering': ['-fecha_vigencia_fin'],
            },
        ),
        migrations.CreateModel(
            name='PolizaSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poliza', models.CharField(max_length=100, verbose_name='número de póliza')),
                ('fecha_vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='inicio de vigencia')),
                ('fecha_vigencia_fin', models.DateField(verbose_name='fin de vigencia')),
                ('importe_prima', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='importe de prima')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polizas', to='actores.aseguradora', verbose_name='aseguradora')),
                ('titular_poliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='polizas', to='actores.titularpoliza', verbose_name='titular')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to='vehiculos.vehiculo', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'póliza de seguro',
                'verbose_name_plural': 'pólizas de seguro',
                'ordering': ['-fecha_vigencia_fin'],
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_observacion', models.CharField(choices=[('GENERAL', 'General'), ('OPERATIVA', 'Operativa'), ('MECANICA', 'Mecánica'), ('SEGURO', 'Seguro'), ('GPS', 'GPS'), ('ADEUDO', 'Adeudo'), ('SINIESTRO', 'Siniestro'), ('DOCUMENTO', 'Documento')], max_length=50, verbose_name='tipo')),
                ('texto_observacion', models.TextField(verbose_name='observación')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de registro')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autor_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_flotilla', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('poliza_seguro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones', to='vehiculos.polizaseguro', verbose_name='póliza relacionada')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='vehiculos.vehiculo', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'observación',
                'verbose_name_plural': 'observaciones',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddField(
            model_name='emplacamiento',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplacamientos', to='vehiculos.vehiculo', verbose_name='vehículo'),
        ),
        migrations.CreateModel(
            name='Adquisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_adquisicion', models.CharField(max_length=80, verbose_name='tipo de adquisición')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True, verbose_name='fecha de adquisición')),
                ('importe_adquisicion', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='importe')),
                ('observacion_adquisicion', models.TextField(blank=True, null=True, verbose_name='observación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adquisiciones', to='vehiculos.vehiculo', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'adquisición',
                'verbose_name_plural': 'adquisiciones',
                'ordering': ['-fecha_adquisicion'],
            },
        ),
        migrations.CreateModel(
            name='AdeudoVehicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_adeudo', models.CharField(max_length=80, verbose_name='tipo de adeudo')),
                ('monto_adeudo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto')),
                ('estatus_adeudo', models.CharField(choices=[('SIN_ADEUDO', 'Sin adeudo'), ('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado'), ('DESCONOCIDO', 'Desconocido')], default='PENDIENTE', max_length=30, verbose_name='estatus')),
                ('fecha_consulta', models.DateField(blank=True, null=True, verbose_name='fecha de consulta')),
                ('observacion_adeudo', models.TextField(blank=True, null=True, verbose_name='observación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adeudos', to='vehiculos.vehiculo', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'adeudo vehicular',
                'verbose_name_plural': 'adeudos vehiculares',
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.CreateModel(
            name='VerificacionVehicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(help_text='Ejemplo: 2024-1, 2024-2', max_length=20, verbose_name='semestre')),
                ('fecha_ultima_verificacion', models.DateField(blank=True, null=True, verbose_name='fecha de última verificación')),
                ('fecha_limite_verificacion', models.DateField(verbose_name='fecha límite de verificación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('emplacamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verificaciones', to='vehiculos.emplacamiento', verbose_name='emplacamiento relacionado')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificaciones', to='vehiculos.vehiculo', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'verificación vehicular',
                'verbose_name_plural': 'verificaciones vehiculares',
                'ordering': ['-fecha_limite_verificacion'],
            },
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['estatus_unidad'], name='idx_vehiculo_estatus'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['modelo_vehiculo', 'color', 'anio_modelo'], name='idx_vehiculo_modelo_color_anio'),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.CheckConstraint(condition=models.Q(('estatus_unidad__in', ['ACTIVA', 'BAJA', 'TALLER', 'SIN_ASIGNAR', 'SINIESTRADA', 'VENDIDA'])), name='chk_vehiculo_estatus'),
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.CheckConstraint(condition=models.Q(('anio_modelo__gte', 1900), ('anio_modelo__lte', 2100)), name='chk_vehiculo_anio_modelo'),
        ),
        migrations.AddIndex(
            model_name='tenencia',
            index=models.Index(fields=['vehiculo'], name='idx_tenencia_vehiculo'),
        ),
        migrations.AddIndex(
            model_name='tenencia',
            index=models.Index(fields=['anio_fiscal'], name='idx_tenencia_anio'),
        ),
        migrations.AddIndex(
            model_name='tenencia',
            index=models.Index(fields=['estatus_tenencia'], name='idx_tenencia_estatus'),
        ),
        migrations.AddConstraint(
            model_name='tenencia',
            constraint=models.UniqueConstraint(fields=('vehiculo', 'anio_fiscal'), name='uq_tenencia_vehiculo_anio'),
        ),
        migrations.AddConstraint(
            model_name='tenencia',
            constraint=models.CheckConstraint(condition=models.Q(('estatus_tenencia__in', ['PAGADA', 'PENDIENTE', 'NO_APLICA', 'DESCONOCIDA'])), name='chk_tenencia_estatus'),
        ),
        migrations.AddConstraint(
            model_name='tenencia',
            constraint=models.CheckConstraint(condition=models.Q(('monto_tenencia__isnull', True), ('monto_tenencia__gte', 0), _connector='OR'), name='chk_tenencia_monto'),
        ),
        migrations.AddConstraint(
            model_name='tenencia',
            constraint=models.CheckConstraint(condition=models.Q(('anio_fiscal__gte', 1900), ('anio_fiscal__lte', 2100)), name='chk_tenencia_anio_fiscal'),
        ),
        migrations.AddIndex(
            model_name='tarjetacirculacion',
            index=models.Index(fields=['vehiculo'], name='idx_tarjeta_vehiculo'),
        ),
        migrations.AddIndex(
            model_name='tarjetacirculacion',
            index=models.Index(fields=['fecha_vigencia_fin'], name='idx_tarjeta_vigencia'),
        ),
        migrations.AddConstraint(
            model_name='tarjetacirculacion',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_emision__isnull', True), ('fecha_vigencia_fin__gte', models.F('fecha_emision')), _connector='OR'), name='chk_tarjeta_fechas'),
        ),
        migrations.AddIndex(
            model_name='polizaseguro',
            index=models.Index(fields=['vehiculo'], name='idx_poliza_vehiculo'),
        ),
        migrations.AddIndex(
            model_name='polizaseguro',
            index=models.Index(django.db.models.functions.text.Upper('numero_poliza'), name='idx_poliza_numero'),
        ),
        migrations.AddIndex(
            model_name='polizaseguro',
            index=models.Index(fields=['fecha_vigencia_fin'], name='idx_poliza_vigencia_fin'),
        ),
        migrations.AddConstraint(
            model_name='polizaseguro',
            constraint=models.UniqueConstraint(fields=('aseguradora', 'numero_poliza'), name='uq_poliza_por_aseguradora'),
        ),
        migrations.AddConstraint(
            model_name='polizaseguro',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_vigencia_inicio__isnull', True), ('fecha_vigencia_fin__gte', models.F('fecha_vigencia_inicio')), _connector='OR'), name='chk_poliza_fechas'),
        ),
        migrations.AddConstraint(
            model_name='polizaseguro',
            constraint=models.CheckConstraint(condition=models.Q(('importe_prima__isnull', True), ('importe_prima__gte', 0), _connector='OR'), name='chk_poliza_importe'),
        ),
        migrations.AddIndex(
            model_name='observacion',
            index=models.Index(fields=['vehiculo'], name='idx_observacion_vehiculo'),
        ),
        migrations.AddIndex(
            model_name='observacion',
            index=models.Index(fields=['tipo_observacion'], name='idx_observacion_tipo'),
        ),
        migrations.AddIndex(
            model_name='observacion',
            index=models.Index(fields=['fecha_registro'], name='idx_observacion_fecha'),
        ),
        migrations.AddConstraint(
            model_name='observacion',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_observacion__in', ['GENERAL', 'OPERATIVA', 'MECANICA', 'SEGURO', 'GPS', 'ADEUDO', 'SINIESTRO', 'DOCUMENTO'])), name='chk_observacion_tipo'),
        ),
        migrations.AddIndex(
            model_name='emplacamiento',
            index=models.Index(django.db.models.functions.text.Upper('placas'), name='idx_emplacamiento_placas'),
        ),
        migrations.AddIndex(
            model_name='emplacamiento',
            index=models.Index(fields=['vehiculo'], name='idx_emplacamiento_vehiculo'),
        ),
        migrations.AddConstraint(
            model_name='emplacamiento',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_fin__isnull', True)), fields=('vehiculo',), name='uq_emplacamiento_actual_por_vehiculo'),
        ),
        migrations.AddConstraint(
            model_name='emplacamiento',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('placas'), condition=models.Q(('fecha_fin__isnull', True)), name='uq_emplacamiento_placa_actual'),
        ),
        migrations.AddConstraint(
            model_name='emplacamiento',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_inicio__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='chk_emplacamiento_fechas'),
        ),
        migrations.AddIndex(
            model_name='adquisicion',
            index=models.Index(fields=['vehiculo'], name='idx_adquisicion_vehiculo'),
        ),
        migrations.AddIndex(
            model_name='adquisicion',
            index=models.Index(fields=['fecha_adquisicion'], name='idx_adquisicion_fecha'),
        ),
        migrations.AddConstraint(
            model_name='adquisicion',
            constraint=models.CheckConstraint(condition=models.Q(('importe_adquisicion__isnull', True), ('importe_adquisicion__gte', 0), _connector='OR'), name='chk_adquisicion_importe'),
        ),
        migrations.AddIndex(
            model_name='adeudovehicular',
            index=models.Index(fields=['vehiculo'], name='idx_adeudo_vehiculo'),
        ),
        migrations.AddIndex(
            model_name='adeudovehicular',
            index=models.Index(fields=['estatus_adeudo'], name='idx_adeudo_estatus'),
        ),
        migrations.AddIndex(
            model_name='adeudovehicular',
            index=models.Index(django.db.models.functions.text.Upper('tipo_adeudo'), name='idx_adeudo_tipo'),
        ),
        migrations.AddConstraint(
            model_name='adeudovehicular',
            constraint=models.CheckConstraint(condition=models.Q(('monto_adeudo__isnull', True), ('monto_adeudo__gte', 0), _connector='OR'), name='chk_adeudo_monto'),
        ),
        migrations.AddConstraint(
            model_name='adeudovehicular',
            constraint=models.CheckConstraint(condition=models.Q(('estatus_adeudo__in', ['SIN_ADEUDO', 'PENDIENTE', 'PAGADO', 'CANCELADO', 'DESCONOCIDO'])), name='chk_adeudo_estatus'),
        ),
        migrations.AddIndex(
            model_name='verificacionvehicular',
            index=models.Index(fields=['vehiculo'], name='idx_verificacion_vehiculo'),
        ),
        migrations.AddIndex(
            model_name='verificacionvehicular',
            index=models.Index(fields=['fecha_limite_verificacion'], name='idx_verificacion_limite'),
        ),
        migrations.AddIndex(
            model_name='verificacionvehicular',
            index=models.Index(fields=['semestre'], name='idx_verificacion_semestre'),
        ),
    ]
