# Generated by Django 5.2.15 on 2026-06-23 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0001_initial'),
        ('vehiculos', '0002_observacion_fk_instalacion_gps'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion',
            name='asignacion_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones', to='operacion.asignacionvehiculo', verbose_name='asignación relacionada'),
        ),
    ]
