# Generated by Django 5.2.15 on 2026-06-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_vistas_bd'),
    ]

    operations = [
        migrations.CreateModel(
            name='VwFichaVehiculo',
            fields=[
                ('id_vehiculo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('numero_interno', models.CharField(blank=True, max_length=50, null=True)),
                ('clave_vehiculo', models.TextField(blank=True, null=True)),
                ('nombre_marca', models.CharField(max_length=80)),
                ('nombre_modelo_comercial', models.CharField(max_length=120)),
                ('version', models.CharField(blank=True, max_length=80, null=True)),
                ('anio_modelo', models.SmallIntegerField()),
                ('nombre_color', models.CharField(max_length=50)),
                ('numero_serie', models.CharField(max_length=40)),
                ('placas_actuales', models.CharField(blank=True, max_length=20, null=True)),
                ('entidad_emplacamiento_actual', models.CharField(blank=True, max_length=80, null=True)),
                ('conductor', models.CharField(blank=True, max_length=255, null=True)),
                ('plataforma', models.CharField(blank=True, max_length=255, null=True)),
                ('socio', models.CharField(blank=True, max_length=255, null=True)),
                ('cuenta', models.CharField(blank=True, max_length=120, null=True)),
                ('numero_poliza', models.CharField(blank=True, max_length=100, null=True)),
                ('vigencia_poliza', models.DateField(blank=True, null=True)),
                ('semestre_verificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_ultima_verificacion', models.DateField(blank=True, null=True)),
                ('fecha_limite_verificacion', models.DateField(blank=True, null=True)),
                ('vigencia_tarjeta_circulacion', models.DateField(blank=True, null=True)),
                ('cantidad_adeudos_pendientes', models.IntegerField(default=0)),
                ('monto_adeudos_pendientes', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('semaforo_documental', models.CharField(max_length=10)),
                ('estatus_unidad', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'ficha de vehículo',
                'verbose_name_plural': 'fichas de vehículos',
                'db_table': 'vw_ficha_vehiculo',
                'ordering': ['numero_interno', 'numero_serie'],
                'managed': False,
            },
        ),
    ]
