# Generated by Django 5.2.15 on 2026-06-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_vw_ficha_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='numero_interno',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='número interno'),
        ),
    ]
