# Generated by Django 5.2.15 on 2026-06-23 06:50

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actores', '0001_initial'),
        ('catalogos', '0002_datos_iniciales'),
        ('vehiculos', '0002_observacion_fk_instalacion_gps'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(blank=True, max_length=100, null=True, verbose_name='cuenta operativa')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='fecha fin')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_vehiculo', to='actores.conductor', verbose_name='conductor')),
                ('plataforma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_vehiculo', to='actores.plataformaoperativa', verbose_name='plataforma operativa')),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_vehiculo', to='actores.socio', verbose_name='socio')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_vehiculo', to='vehiculos.vehiculo', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'asignación de vehículo',
                'verbose_name_plural': 'asignaciones de vehículo',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus_app_asignada', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('SUSPENDIDA', 'Suspendida')], default='ACTIVA', max_length=30, verbose_name='estatus')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('app_transporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_app', to='catalogos.apptransporte', verbose_name='app de transporte')),
                ('asignacion_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps_asignadas', to='operacion.asignacionvehiculo', verbose_name='asignación de vehículo')),
            ],
            options={
                'verbose_name': 'app asignada',
                'verbose_name_plural': 'apps asignadas',
                'ordering': ['app_transporte__nombre_app'],
            },
        ),
        migrations.AddIndex(
            model_name='asignacionvehiculo',
            index=models.Index(fields=['vehiculo'], name='idx_asignacion_vehiculo'),
        ),
        migrations.AddIndex(
            model_name='asignacionvehiculo',
            index=models.Index(fields=['conductor'], name='idx_asignacion_conductor'),
        ),
        migrations.AddIndex(
            model_name='asignacionvehiculo',
            index=models.Index(fields=['plataforma'], name='idx_asignacion_plataforma'),
        ),
        migrations.AddIndex(
            model_name='asignacionvehiculo',
            index=models.Index(fields=['socio'], name='idx_asignacion_socio'),
        ),
        migrations.AddIndex(
            model_name='asignacionvehiculo',
            index=models.Index(django.db.models.functions.text.Upper('cuenta'), name='idx_asignacion_cuenta'),
        ),
        migrations.AddConstraint(
            model_name='asignacionvehiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_fin__isnull', True)), fields=('vehiculo',), name='uq_asignacion_actual_por_vehiculo'),
        ),
        migrations.AddConstraint(
            model_name='asignacionvehiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_fin__isnull', True)), fields=('conductor',), name='uq_asignacion_actual_por_conductor'),
        ),
        migrations.AddConstraint(
            model_name='asignacionvehiculo',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_inicio__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='chk_asignacion_vehiculo_fechas'),
        ),
        migrations.AddConstraint(
            model_name='asignacionapp',
            constraint=models.UniqueConstraint(fields=('asignacion_vehiculo', 'app_transporte'), name='uq_asignacion_app'),
        ),
        migrations.AddConstraint(
            model_name='asignacionapp',
            constraint=models.CheckConstraint(condition=models.Q(('estatus_app_asignada__in', ['ACTIVA', 'INACTIVA', 'SUSPENDIDA'])), name='chk_asignacion_app_estatus'),
        ),
    ]
