# Generated by Django 5.2.15 on 2026-06-23 06:46

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoGps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=80, unique=True, verbose_name='IMEI')),
                ('numero_gps', models.CharField(blank=True, max_length=80, null=True, verbose_name='número GPS')),
                ('estatus_gps', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('EXTRAVIADO', 'Extraviado'), ('DANADO', 'Dañado'), ('BAJA', 'Baja')], default='ACTIVO', max_length=30, verbose_name='estatus')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'dispositivo GPS',
                'verbose_name_plural': 'dispositivos GPS',
                'ordering': ['imei'],
                'indexes': [models.Index(django.db.models.functions.text.Upper('imei'), name='idx_gps_imei')],
                'constraints': [models.CheckConstraint(condition=models.Q(('estatus_gps__in', ['ACTIVO', 'INACTIVO', 'EXTRAVIADO', 'DANADO', 'BAJA'])), name='chk_gps_estatus')],
            },
        ),
        migrations.CreateModel(
            name='TagTelepeaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tag', models.CharField(max_length=100, unique=True, verbose_name='código TAG')),
                ('codigo_tag_corto', models.CharField(blank=True, max_length=100, null=True, verbose_name='código corto')),
                ('estatus_tag', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('EXTRAVIADO', 'Extraviado'), ('DANADO', 'Dañado'), ('BAJA', 'Baja')], default='ACTIVO', max_length=30, verbose_name='estatus')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TAG de telepeaje',
                'verbose_name_plural': 'TAGs de telepeaje',
                'ordering': ['codigo_tag'],
                'indexes': [models.Index(django.db.models.functions.text.Upper('codigo_tag'), name='idx_tag_codigo'), models.Index(django.db.models.functions.text.Upper('codigo_tag_corto'), name='idx_tag_codigo_corto')],
                'constraints': [models.CheckConstraint(condition=models.Q(('estatus_tag__in', ['ACTIVO', 'INACTIVO', 'EXTRAVIADO', 'DANADO', 'BAJA'])), name='chk_tag_estatus')],
            },
        ),
        migrations.CreateModel(
            name='InstalacionGps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='fecha de instalación')),
                ('fecha_retiro', models.DateField(blank=True, null=True, verbose_name='fecha de retiro')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('gps', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instalaciones', to='dispositivos.dispositivogps', verbose_name='dispositivo GPS')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones_gps', to='vehiculos.vehiculo', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'instalación GPS',
                'verbose_name_plural': 'instalaciones GPS',
                'ordering': ['-fecha_instalacion'],
                'indexes': [models.Index(fields=['vehiculo'], name='idx_instalacion_gps_vehiculo'), models.Index(fields=['gps'], name='idx_instalacion_gps_disp')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('fecha_retiro__isnull', True)), fields=('vehiculo',), name='uq_gps_actual_por_vehiculo'), models.UniqueConstraint(condition=models.Q(('fecha_retiro__isnull', True)), fields=('gps',), name='uq_gps_actual_por_dispositivo'), models.CheckConstraint(condition=models.Q(('fecha_retiro__isnull', True), ('fecha_instalacion__isnull', True), ('fecha_retiro__gte', models.F('fecha_instalacion')), _connector='OR'), name='chk_instalacion_gps_fechas')],
            },
        ),
        migrations.CreateModel(
            name='AsignacionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='fecha fin')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_tag', to='vehiculos.vehiculo', verbose_name='vehículo')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='dispositivos.tagtelepeaje', verbose_name='TAG')),
            ],
            options={
                'verbose_name': 'asignación TAG',
                'verbose_name_plural': 'asignaciones TAG',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['vehiculo'], name='idx_asignacion_tag_vehiculo'), models.Index(fields=['tag'], name='idx_asignacion_tag_tag')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('fecha_fin__isnull', True)), fields=('vehiculo',), name='uq_tag_actual_por_vehiculo'), models.UniqueConstraint(condition=models.Q(('fecha_fin__isnull', True)), fields=('tag',), name='uq_tag_actual_por_codigo'), models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_inicio__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='chk_asignacion_tag_fechas')],
            },
        ),
    ]
